name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.0]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 18.15.0
      - run: npm install
      - run: npm run test-lib
      - run: npm run build-lib
      - run: npm run build-app
        env:
          CI: true
